/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.grocerystore.form;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author My PC
 */
public class FormPopupNotification extends javax.swing.JFrame {
    private static final int WIDTH = 300;
    private static final int HEIGHT = 100;
    private float opacity = 0f;
    private Timer timer;
    private Action action = Action.WAIT;
    private Type type = Type.INFO;

    public enum Action {
        WAIT,
        START,
        CLOSE
    }

    public enum Type {
        SUCCESS,
        WARNING,
        ERROR,
        INFO
    }

    /**
     * Creates new form FormPopupNotification
     * @param message
     * @param type
     */
    public FormPopupNotification(String message, Type type) {
        initComponents();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        double width = screenSize.getWidth();
        double height = screenSize.getHeight();
        // Set the location of the window to the bottom right corner
        setLocation((int)width - WIDTH-80, (int)height - HEIGHT-20);
        
        lblMessage.setText(message);
        
        this.type = type;
        switch (type) {
            case SUCCESS:
                getContentPane().setBackground(new Color(51, 153, 51));
                lbl_icon.setIcon(new ImageIcon(getClass().getResource("/com/grocerystore/icon/success.png")));
                break;
            case WARNING:
                getContentPane().setBackground(Color.ORANGE);
                lbl_icon.setIcon(new ImageIcon(getClass().getResource("/com/grocerystore/icon/warning.png")));
                break;
            case ERROR:
                getContentPane().setBackground(Color.RED);
                lbl_icon.setIcon(new ImageIcon(getClass().getResource("/com/grocerystore/icon/error.png")));
                break;
            case INFO:
                getContentPane().setBackground(Color.BLUE);
                lbl_icon.setIcon(new ImageIcon(getClass().getResource("/com/grocerystore/icon/info.png")));
                break;
        }
        this.action = Action.START;
        setOpacity(opacity);
        timer = new Timer(10, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                switch (action) {
                    case WAIT:
                        timer.stop();
                        Timer waitTimer = new Timer(2000, new ActionListener() {
                            @Override
                            public void actionPerformed(ActionEvent e) {
                                action = Action.CLOSE;
                                timer.start();
                                ((Timer)e.getSource()).stop();
                            }
                        });
                        waitTimer.setRepeats(false);
                        waitTimer.start();
                        break;
                    case START:
                        opacity += 0.1f;
                        if (opacity >= 1f) {
                            opacity = 1f;
                            action = Action.WAIT;
                        }
                        break;
                    case CLOSE:
                        opacity -= 0.1f;
                        setLocation(getX() - 3, getY());
                        if (opacity <= 0f) {
                            opacity = 0f;
                            timer.stop();
                            dispose();
                        }
                        break;
                }
                setOpacity(opacity);
            }
        });
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMessage = new javax.swing.JLabel();
        lbl_close = new javax.swing.JLabel();
        lbl_icon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        lblMessage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMessage.setForeground(new java.awt.Color(255, 255, 255));
        lblMessage.setText("jLabel1");

        lbl_close.setIcon(new javax.swing.ImageIcon("D:\\DH_SPKT\\Nam_3\\Ki_1\\Database_ManagementSystem\\Final-Project\\Nhom13_QLCuaHangVPP\\QuanLyCuaHangBanDoChoi\\Resources\\close.png")); // NOI18N
        lbl_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_closeMouseClicked(evt);
            }
        });

        lbl_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/grocerystore/icon/success.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_close, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_close, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_closeMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_lbl_closeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPopupNotification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPopupNotification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPopupNotification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPopupNotification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPopupNotification("Hóa đơn mới đã được thêm", FormPopupNotification.Type.SUCCESS).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lbl_close;
    private javax.swing.JLabel lbl_icon;
    // End of variables declaration//GEN-END:variables
}
